### ISSUE TITLE
`WriteInto` bound breakage after upgrading from 0.11.0 to 0.11.1

### ISSUE THREAD

**Issue by oskarbraten** [teoxoy/encase#101]
Upgrading from 0.11.0 to 0.11.1 broke a generic function that was previously working.

Here's the compiler error after the upgrade:
```rust
error[E0277]: the trait bound `[T]: encase::ShaderType` is not satisfied
   --> main.rs:22:30
    |
376 |         storage_buffer.write(&items[..1]).unwrap();
    |                        ----- ^^^^^^^^^^^ the trait `encase::ShaderType` is not implemented for `[T]`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the following other types implement trait `encase::ShaderType`:
              &[T]
              [T; N]
```

Here's a minimal reproduction:
```rust
use encase::{ShaderSize, ShaderType, StorageBuffer, internal::WriteInto};

pub fn produce_error<T>(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    items: &[T],
) -> wgpu::Buffer
where
    T: ShaderType + ShaderSize + WriteInto,
{
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: items.as_ref().size().into(),
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::STORAGE,
        mapped_at_creation: false,
    });

    {
        let mut view = queue.write_buffer_with(&buffer, 0, T::SHADER_SIZE).unwrap();
        let mut storage_buffer = StorageBuffer::new(view.as_mut());

        storage_buffer.write(&items[..1]).unwrap();
    }

    buffer
}
```

I believe the following change in #97 may be the cause:
```
 - impl_rts_array!([T]; using len);
 + impl_rts_array!(&[T]; using len);
```

As a workaround, I tried adding `for<'a> &'a [T]: WriteInto`, but this just pushes the error to the caller (for example when I try to pass in a `Vec<T>` as a slice).

Is this breakage intentional, or an unintended consequence of the change?

**Comment by teoxoy** [comment]
Thanks for the report! It was not intended. I released v0.11.2 and yanked v0.11.1.
